uniform R3_VERTEX_PRECISION mat4 u_localMat;
uniform R3_VERTEX_PRECISION mat4 u_modelMat;
uniform R3_VERTEX_PRECISION mat4 u_viewMat;
uniform R3_VERTEX_PRECISION mat4 u_projMat;
uniform R3_VERTEX_PRECISION mat4 u_MVMat;
uniform R3_VERTEX_PRECISION mat4 u_MVPMat;
uniform R3_VERTEX_PRECISION mat3 u_normalMat;
uniform R3_VERTEX_PRECISION vec3 u_cameraPos;
uniform R3_VERTEX_PRECISION float u_time;
