export type { IPlatformBuffer } from "./IPlatformBuffer";
export type { IPlatformBufferReadback } from "./IPlatformBufferReadback";
export type { IPlatformRenderTarget } from "./IPlatformRenderTarget";
export type { IPlatformTexture } from "./IPlatformTexture";
export type { IPlatformTexture2D } from "./IPlatformTexture2D";
export type { IPlatformTexture2DArray } from "./IPlatformTexture2DArray";
export type { IPlatformTextureCube } from "./IPlatformTextureCube";
export type { IPlatformTransformFeedback } from "./IPlatformTransformFeedback";
export type { IPlatformTransformFeedbackPrimitive } from "./IPlatformTransformFeedbackPrimitive";
