/**
 *  The type of the pointer.
 */
export enum PointerType {
  /** The event was generated by a mouse device. */
  mouse,
  /** The event was generated by a pen or stylus device. */
  pen,
  /** The event was generated by a touch, such as a finger. */
  touch
}
