/** Shader names, properties, and visual tuning for the first Ocean Gerstner path. */
import { WATER_OPTICS_SHADER_PROPERTY } from "../../optics/constants/WaterOpticsShaderConstants";

export const WATER_WAVE_SHADER_PROPERTY = {
  baseColor: "material_BaseColor",
  deepColor: "material_DeepColor",
  alpha: "material_Alpha",
  waterLevel: "material_WaterLevel",
  timeScale: "material_TimeScale",
  crestIntensity: "material_CrestIntensity",
  reflectionIntensity: WATER_OPTICS_SHADER_PROPERTY.reflectionIntensity,
  reflectionIntensityMultiplier: "material_ReflectionIntensityMultiplier",
  absorptionCoefficient: WATER_OPTICS_SHADER_PROPERTY.absorptionCoefficient,
  scatteringColor: WATER_OPTICS_SHADER_PROPERTY.scatteringColor,
  scatteringCoefficient: WATER_OPTICS_SHADER_PROPERTY.scatteringCoefficient,
  maximumSurfaceOpticalDistance: WATER_OPTICS_SHADER_PROPERTY.maximumSurfaceOpticalDistance,
  indexOfRefraction: WATER_OPTICS_SHADER_PROPERTY.indexOfRefraction,
  refractionStrength: WATER_OPTICS_SHADER_PROPERTY.refractionStrength,
  refractionEnabled: WATER_OPTICS_SHADER_PROPERTY.refractionEnabled,
  roughness: WATER_OPTICS_SHADER_PROPERTY.roughness,
  reflectionSource: WATER_OPTICS_SHADER_PROPERTY.reflectionSource,
  reflectionCubeTexture: WATER_OPTICS_SHADER_PROPERTY.reflectionCubeTexture,
  planarReflectionTexture: WATER_OPTICS_SHADER_PROPERTY.planarReflectionTexture,
  planarReflectionViewProjection: WATER_OPTICS_SHADER_PROPERTY.planarReflectionViewProjection,
  planarReflectionTextureSize: WATER_OPTICS_SHADER_PROPERTY.planarReflectionTextureSize,
  planarReflectionSampling: WATER_OPTICS_SHADER_PROPERTY.planarReflectionSampling,
  planarReflectionFade: WATER_OPTICS_SHADER_PROPERTY.planarReflectionFade,
  planarReflectionRoughnessFootprint: WATER_OPTICS_SHADER_PROPERTY.planarReflectionRoughnessFootprint,
  surfaceTimeOverride: "material_SurfaceTimeOverride",
  maxVerticalDisplacement: "material_MaxVerticalDisplacement",
  waveAPrefix: "material_WaveA",
  waveBPrefix: "material_WaveB"
} as const;

export const WATER_WAVE_SHADER_TUNING = {
  deepColorScale: 0.34,
  deepColorBlueLift: 0.08,
  horizonColorScale: 1.2,
  fresnelPower: 5,
  fresnelStrength: 0.38,
  diffuseFloor: 0.48,
  diffuseNormalWeight: 0.42,
  specularPower: 36,
  specularStrength: 0.68,
  crestTintStrength: 0.52,
  slopeContrast: 8,
  slopeDirectionalStrength: 0.36,
  mediumRefractionUvScale: 0.006,
  highRefractionUvScale: 0.009,
  mediumRefractionMix: 0.58,
  highRefractionMix: 0.7,
  refractionDepthStart: 0.04,
  refractionDepthEnd: 1.15,
  refractionDepthToleranceMinimum: 0.18,
  refractionDepthToleranceScale: 0.45,
  refractionEdgeInset: 0.002,
  minimumAlpha: 0.05,
  maximumAlpha: 1,
  lightDirection: [0.38, 0.86, 0.34] as const
} as const;
