/** Shader names, properties, and visual tuning for the first Ocean Gerstner path. */
import { WATER_OPTICS_SHADER_PROPERTY } from "../../optics/constants/WaterOpticsShaderConstants";

export const WATER_WAVE_SHADER_PROPERTY = {
  baseColor: "material_BaseColor",
  deepColor: "material_DeepColor",
  alpha: "material_Alpha",
  waterLevel: "material_WaterLevel",
  timeScale: "material_TimeScale",
  crestIntensity: "material_CrestIntensity",
  reflectionIntensity: WATER_OPTICS_SHADER_PROPERTY.reflectionIntensity,
  reflectionIntensityMultiplier: "material_ReflectionIntensityMultiplier",
  absorptionCoefficient: WATER_OPTICS_SHADER_PROPERTY.absorptionCoefficient,
  scatteringColor: WATER_OPTICS_SHADER_PROPERTY.scatteringColor,
  scatteringCoefficient: WATER_OPTICS_SHADER_PROPERTY.scatteringCoefficient,
  maximumSurfaceOpticalDistance: WATER_OPTICS_SHADER_PROPERTY.maximumSurfaceOpticalDistance,
  indexOfRefraction: WATER_OPTICS_SHADER_PROPERTY.indexOfRefraction,
  refractionStrength: WATER_OPTICS_SHADER_PROPERTY.refractionStrength,
  refractionEnabled: WATER_OPTICS_SHADER_PROPERTY.refractionEnabled,
  roughness: WATER_OPTICS_SHADER_PROPERTY.roughness,
  reflectionSource: WATER_OPTICS_SHADER_PROPERTY.reflectionSource,
  reflectionCubeTexture: WATER_OPTICS_SHADER_PROPERTY.reflectionCubeTexture,
  planarReflectionTexture: WATER_OPTICS_SHADER_PROPERTY.planarReflectionTexture,
  planarReflectionViewProjection: WATER_OPTICS_SHADER_PROPERTY.planarReflectionViewProjection,
  planarReflectionTextureSize: WATER_OPTICS_SHADER_PROPERTY.planarReflectionTextureSize,
  planarReflectionSampling: WATER_OPTICS_SHADER_PROPERTY.planarReflectionSampling,
  planarReflectionFade: WATER_OPTICS_SHADER_PROPERTY.planarReflectionFade,
  planarReflectionRoughnessFootprint: WATER_OPTICS_SHADER_PROPERTY.planarReflectionRoughnessFootprint,
  surfaceDetailTexture: "material_SurfaceDetailTexture",
  surfaceDetailEnabled: "material_SurfaceDetailEnabled",
  surfaceDetailStrength: "material_SurfaceDetailStrength",
  surfaceDetailScale: "material_SurfaceDetailScale",
  surfaceDetailSpeed: "material_SurfaceDetailSpeed",
  surfaceDetailWind: "material_SurfaceDetailWind",
  nearshoreTexture: "material_NearshoreTexture",
  nearshoreEnabled: "material_NearshoreEnabled",
  nearshoreWorldToUv: "material_NearshoreWorldToUv",
  nearshoreDecode: "material_NearshoreDecode",
  nearshoreGrid: "material_NearshoreGrid",
  nearshoreOutsidePolicy: "material_NearshoreOutsidePolicy",
  nearshoreDebugView: "material_NearshoreDebugView",
  nearshoreWaveEnabled: "material_NearshoreWaveEnabled",
  nearshoreStateTexture: "material_NearshoreStateTexture",
  nearshoreWetnessTexture: "material_NearshoreWetnessTexture",
  nearshoreStateEnabled: "material_NearshoreStateEnabled",
  nearshoreBreakerEnabled: "material_NearshoreBreakerEnabled",
  nearshoreStateDecode: "material_NearshoreStateDecode",
  temporalFoamTexture: "material_TemporalFoamTexture",
  temporalFoamEnabled: "material_TemporalFoamEnabled",
  foamDetailTexture: "material_FoamDetailTexture",
  foamDetailEnabled: "material_FoamDetailEnabled",
  temporalFoamRegion: "material_TemporalFoamRegion",
  temporalFoamTexelSize: "material_TemporalFoamTexelSize",
  foamDebugView: "material_FoamDebugView",
  analyticWhitecapEnabled: "material_AnalyticWhitecapEnabled",
  surfaceTimeOverride: "material_SurfaceTimeOverride",
  maxVerticalDisplacement: "material_MaxVerticalDisplacement",
  waveAPrefix: "material_WaveA",
  waveBPrefix: "material_WaveB"
} as const;

export const WATER_WAVE_SHADER_TUNING = {
  deepColorScale: 0.24,
  deepColorBlueLift: 0.035,
  horizonColorScale: 0.92,
  fresnelPower: 5,
  fresnelStrength: 0.38,
  diffuseFloor: 0.34,
  diffuseNormalWeight: 0.38,
  directSpecularStrength: 0.2,
  minimumPerceptualRoughness: 0.045,
  brdfEpsilon: 0.000001,
  surfaceDetailTimePeriod: 4096,
  surfaceDetailLayerScales: [1, 2.37, 5.13] as const,
  surfaceDetailLayerRates: [1, -0.63, 1.41] as const,
  surfaceDetailLayerWeights: [0.55, 0.3, 0.15] as const,
  surfaceDetailCrossWind: [0.19, -0.37, 0.61] as const,
  crestTintStrength: 0.8,
  slopeContrast: 5.5,
  slopeDirectionalStrength: 0.22,
  mediumRefractionUvScale: 0.006,
  highRefractionUvScale: 0.009,
  mediumRefractionMix: 0.58,
  highRefractionMix: 0.7,
  refractionDepthStart: 0.04,
  refractionDepthEnd: 1.15,
  refractionDepthToleranceMinimum: 0.18,
  refractionDepthToleranceScale: 0.45,
  refractionEdgeInset: 0.002,
  minimumAlpha: 0.05,
  maximumAlpha: 1
} as const;
