// Auto-generated by scripts/generate-source-indexes.js — do not edit.
// path is relative to packages/shader/src/.

import _2D_Sprite from "./2D/Sprite.shader";
import _2D_SpriteMask from "./2D/SpriteMask.shader";
import _2D_Text from "./2D/Text.shader";
import _2D_UIDefault from "./2D/UIDefault.shader";
import AO_ScalableAmbientOcclusion from "./AO/ScalableAmbientOcclusion.shader";
import BlinnPhong from "./BlinnPhong.shader";
import Effect_Particle from "./Effect/Particle.shader";
import Effect_ParticleFeedback from "./Effect/ParticleFeedback.shader";
import Effect_Trail from "./Effect/Trail.shader";
import PBR from "./PBR.shader";
import PostProcess_Bloom from "./PostProcess/Bloom.shader";
import PostProcess_FinalAntiAliasing from "./PostProcess/FinalAntiAliasing.shader";
import PostProcess_FinalSRGB from "./PostProcess/FinalSRGB.shader";
import PostProcess_Uber from "./PostProcess/Uber.shader";
import Sky_BackgroundTexture from "./Sky/BackgroundTexture.shader";
import Sky_SkyProcedural from "./Sky/SkyProcedural.shader";
import Sky_Skybox from "./Sky/Skybox.shader";
import Unlit from "./Unlit.shader";
import Utility_Blit from "./Utility/Blit.shader";
import Utility_BlitScreen from "./Utility/BlitScreen.shader";
import Utility_DepthOnly from "./Utility/DepthOnly.shader";
import Utility_ShadowMap from "./Utility/ShadowMap.shader";

interface IShaderSource {
  path: string;
  source: string;
}

// prettier-ignore
export const shaders: IShaderSource[] = [
  { source: _2D_Sprite, path: "Shaders/2D/Sprite.shader" },
  { source: _2D_SpriteMask, path: "Shaders/2D/SpriteMask.shader" },
  { source: _2D_Text, path: "Shaders/2D/Text.shader" },
  { source: _2D_UIDefault, path: "Shaders/2D/UIDefault.shader" },
  { source: AO_ScalableAmbientOcclusion, path: "Shaders/AO/ScalableAmbientOcclusion.shader" },
  { source: BlinnPhong, path: "Shaders/BlinnPhong.shader" },
  { source: Effect_Particle, path: "Shaders/Effect/Particle.shader" },
  { source: Effect_ParticleFeedback, path: "Shaders/Effect/ParticleFeedback.shader" },
  { source: Effect_Trail, path: "Shaders/Effect/Trail.shader" },
  { source: PBR, path: "Shaders/PBR.shader" },
  { source: PostProcess_Bloom, path: "Shaders/PostProcess/Bloom.shader" },
  { source: PostProcess_FinalAntiAliasing, path: "Shaders/PostProcess/FinalAntiAliasing.shader" },
  { source: PostProcess_FinalSRGB, path: "Shaders/PostProcess/FinalSRGB.shader" },
  { source: PostProcess_Uber, path: "Shaders/PostProcess/Uber.shader" },
  { source: Sky_BackgroundTexture, path: "Shaders/Sky/BackgroundTexture.shader" },
  { source: Sky_SkyProcedural, path: "Shaders/Sky/SkyProcedural.shader" },
  { source: Sky_Skybox, path: "Shaders/Sky/Skybox.shader" },
  { source: Unlit, path: "Shaders/Unlit.shader" },
  { source: Utility_Blit, path: "Shaders/Utility/Blit.shader" },
  { source: Utility_BlitScreen, path: "Shaders/Utility/BlitScreen.shader" },
  { source: Utility_DepthOnly, path: "Shaders/Utility/DepthOnly.shader" },
  { source: Utility_ShadowMap, path: "Shaders/Utility/ShadowMap.shader" },
];
