// Auto-generated by shader-compiler-precompile --emit-sources — do not edit.

import _2D_Sprite from "./2D/Sprite.shader";
import _2D_SpriteMask from "./2D/SpriteMask.shader";
import _2D_Text from "./2D/Text.shader";
import _2D_UIDefault from "./2D/UIDefault.shader";
import BlinnPhong from "./BlinnPhong.shader";
import Blit_Blit from "./Blit/Blit.shader";
import Blit_BlitScreen from "./Blit/BlitScreen.shader";
import Effect_Particle from "./Effect/Particle.shader";
import Effect_ParticleFeedback from "./Effect/ParticleFeedback.shader";
import Effect_Trail from "./Effect/Trail.shader";
import GaussianSplat from "./GaussianSplat.shader";
import Lighting_ScalableAmbientOcclusion from "./Lighting/ScalableAmbientOcclusion.shader";
import PBR from "./PBR.shader";
import Pipeline_DepthOnly from "./Pipeline/DepthOnly.shader";
import Pipeline_ShadowCaster from "./Pipeline/ShadowCaster.shader";
import PostProcess_Bloom from "./PostProcess/Bloom.shader";
import PostProcess_FinalAntiAliasing from "./PostProcess/FinalAntiAliasing.shader";
import PostProcess_FinalSRGB from "./PostProcess/FinalSRGB.shader";
import PostProcess_Uber from "./PostProcess/Uber.shader";
import Sky_BackgroundTexture from "./Sky/BackgroundTexture.shader";
import Sky_SkyProcedural from "./Sky/SkyProcedural.shader";
import Sky_Skybox from "./Sky/Skybox.shader";
import Unlit from "./Unlit.shader";

export interface IShaderSource {
  path: string;
  source: string;
}

// prettier-ignore
export const shaders: IShaderSource[] = [
  { source: _2D_Sprite, path: "Shaders/2D/Sprite.shader" },
  { source: _2D_SpriteMask, path: "Shaders/2D/SpriteMask.shader" },
  { source: _2D_Text, path: "Shaders/2D/Text.shader" },
  { source: _2D_UIDefault, path: "Shaders/2D/UIDefault.shader" },
  { source: BlinnPhong, path: "Shaders/BlinnPhong.shader" },
  { source: Blit_Blit, path: "Shaders/Blit/Blit.shader" },
  { source: Blit_BlitScreen, path: "Shaders/Blit/BlitScreen.shader" },
  { source: Effect_Particle, path: "Shaders/Effect/Particle.shader" },
  { source: Effect_ParticleFeedback, path: "Shaders/Effect/ParticleFeedback.shader" },
  { source: Effect_Trail, path: "Shaders/Effect/Trail.shader" },
  { source: GaussianSplat, path: "Shaders/GaussianSplat.shader" },
  { source: Lighting_ScalableAmbientOcclusion, path: "Shaders/Lighting/ScalableAmbientOcclusion.shader" },
  { source: PBR, path: "Shaders/PBR.shader" },
  { source: Pipeline_DepthOnly, path: "Shaders/Pipeline/DepthOnly.shader" },
  { source: Pipeline_ShadowCaster, path: "Shaders/Pipeline/ShadowCaster.shader" },
  { source: PostProcess_Bloom, path: "Shaders/PostProcess/Bloom.shader" },
  { source: PostProcess_FinalAntiAliasing, path: "Shaders/PostProcess/FinalAntiAliasing.shader" },
  { source: PostProcess_FinalSRGB, path: "Shaders/PostProcess/FinalSRGB.shader" },
  { source: PostProcess_Uber, path: "Shaders/PostProcess/Uber.shader" },
  { source: Sky_BackgroundTexture, path: "Shaders/Sky/BackgroundTexture.shader" },
  { source: Sky_SkyProcedural, path: "Shaders/Sky/SkyProcedural.shader" },
  { source: Sky_Skybox, path: "Shaders/Sky/Skybox.shader" },
  { source: Unlit, path: "Shaders/Unlit.shader" },
];
