// Auto-generated by shader-precompile --emit-index — do not edit
import BackgroundTextureSource from "./Sky/BackgroundTexture.gsp";
import BlinnPhongSource from "./BlinnPhong.gsp";
import BlitScreenSource from "./Blit/BlitScreen.gsp";
import BlitSource from "./Blit/Blit.gsp";
import BloomSource from "./PostProcess/Bloom.gsp";
import DepthOnlySource from "./Pipeline/DepthOnly.gsp";
import FinalAntiAliasingSource from "./PostProcess/FinalAntiAliasing.gsp";
import FinalSRGBSource from "./PostProcess/FinalSRGB.gsp";
import ParticleFeedbackSource from "./Effect/ParticleFeedback.gsp";
import ParticleSource from "./Effect/Particle.gsp";
import PBRSource from "./PBR.gsp";
import ScalableAmbientOcclusionSource from "./Lighting/ScalableAmbientOcclusion.gsp";
import ShadowCasterSource from "./Pipeline/ShadowCaster.gsp";
import SkyboxSource from "./Sky/Skybox.gsp";
import SkyProceduralSource from "./Sky/SkyProcedural.gsp";
import SpriteMaskSource from "./2D/SpriteMask.gsp";
import SpriteSource from "./2D/Sprite.gsp";
import TextSource from "./2D/Text.gsp";
import TrailSource from "./Effect/Trail.gsp";
import UberSource from "./PostProcess/Uber.gsp";
import UIDefaultSource from "./2D/UIDefault.gsp";
import UnlitSource from "./Unlit.gsp";

// prettier-ignore
export {
  BackgroundTextureSource,
  BlinnPhongSource,
  BlitScreenSource,
  BlitSource,
  BloomSource,
  DepthOnlySource,
  FinalAntiAliasingSource,
  FinalSRGBSource,
  ParticleFeedbackSource,
  ParticleSource,
  PBRSource,
  ScalableAmbientOcclusionSource,
  ShadowCasterSource,
  SkyboxSource,
  SkyProceduralSource,
  SpriteMaskSource,
  SpriteSource,
  TextSource,
  TrailSource,
  UberSource,
  UIDefaultSource,
  UnlitSource
};
