// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import BackgroundTextureSource from "./Sky/BackgroundTexture.shaderc";
import BlinnPhongSource from "./BlinnPhong.shaderc";
import BlitScreenSource from "./Blit/BlitScreen.shaderc";
import BlitSource from "./Blit/Blit.shaderc";
import BloomSource from "./PostProcess/Bloom.shaderc";
import DepthOnlySource from "./Pipeline/DepthOnly.shaderc";
import FinalAntiAliasingSource from "./PostProcess/FinalAntiAliasing.shaderc";
import FinalSRGBSource from "./PostProcess/FinalSRGB.shaderc";
import ParticleFeedbackSource from "./Effect/ParticleFeedback.shaderc";
import ParticleSource from "./Effect/Particle.shaderc";
import PBRSource from "./PBR.shaderc";
import ScalableAmbientOcclusionSource from "./Lighting/ScalableAmbientOcclusion.shaderc";
import ShadowCasterSource from "./Pipeline/ShadowCaster.shaderc";
import SkyboxSource from "./Sky/Skybox.shaderc";
import SkyProceduralSource from "./Sky/SkyProcedural.shaderc";
import SpineSource from "./2D/Spine.shaderc";
import SpriteMaskSource from "./2D/SpriteMask.shaderc";
import SpriteSource from "./2D/Sprite.shaderc";
import TextSource from "./2D/Text.shaderc";
import TrailSource from "./Effect/Trail.shaderc";
import UberSource from "./PostProcess/Uber.shaderc";
import UIDefaultSource from "./2D/UIDefault.shaderc";
import UnlitSource from "./Unlit.shaderc";

// prettier-ignore
export {
  BackgroundTextureSource,
  BlinnPhongSource,
  BlitScreenSource,
  BlitSource,
  BloomSource,
  DepthOnlySource,
  FinalAntiAliasingSource,
  FinalSRGBSource,
  ParticleFeedbackSource,
  ParticleSource,
  PBRSource,
  ScalableAmbientOcclusionSource,
  ShadowCasterSource,
  SkyboxSource,
  SkyProceduralSource,
  SpineSource,
  SpriteMaskSource,
  SpriteSource,
  TextSource,
  TrailSource,
  UberSource,
  UIDefaultSource,
  UnlitSource
};
