/**
 * The number of the code in the keyboard event.
 * Keep up with W3C standards.
 * https://www.w3.org/TR/2017/CR-uievents-code-20170601/
 */
export enum KeyCode {
    /** List of code values for writing system keys in the Alphanumeric section. */
    Backquote,
    Backslash,
    Backspace,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,

    /** List of code values for functional keys in the Alphanumeric section. */
    AltLeft,
    AltRight,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    MetaLeft,
    MetaRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,

    /** List of code values for functional keys found on Japanese and Korean keyboards. */
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,

    /** List of code values for keys in the ControlPad section. */
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,

    /** List of code values for keys in the ArrowPad section. */
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,

    /** List of code values for keys in the Numpad section. */
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,

    /** List of code values for keys in the Function section. */
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,

    /** List of code values for media keys. */
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,

    /** List of code values for legacy modifier keys. */
    Hyper,
    Super,
    Turbo,

    /** List of code values for legacy process control keys. */
    Abort,
    Resume,
    Suspend,

    /** List of code values for legacy editing keys. */
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,

    /** List of code values for keys found on international keyboards. */
    Hiragana,
    Katakana,

    /** List of special code values. */
    Unidentified,
}