#!/usr/bin/env node
/**
 * Precompile all built-in .shader files to .gsp (JSON) files.
 * Also cleans up orphaned .gsp files whose .shader source no longer exists.
 *
 * Usage:
 *   node scripts/precompile-shaders.mjs              # full: all shaders + cleanup
 *   node scripts/precompile-shaders.mjs path/to/X.shader  # single file (incremental)
 *
 * Output: packages/shader/libs/<mirrored-path>.gsp
 */

import fs from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SHADERS_DIR = path.join(ROOT, "packages/shader/src/Shaders");
const LIBS_DIR = path.join(ROOT, "packages/shader/libs");

// Provide browser shims so engine-core can load in Node.js
if (typeof globalThis.window === "undefined") {
  globalThis.window = { devicePixelRatio: 1 };
}
if (typeof globalThis.document === "undefined") {
  globalThis.document = { createElement: () => ({}) };
}

import { execSync } from "child_process";

// --index-only: just regenerate libs/index.ts without loading ShaderLab
if (process.argv[2] === "--index-only") {
  generateLibsIndex();
  console.log("Done.");
  process.exit(0);
}

// Ensure shader-lab dist is up-to-date before loading.
const shaderLabDist = path.resolve(ROOT, "packages/shader-lab/dist/main.js");
const shaderLabSrc = path.join(ROOT, "packages/shader-lab/src");

function needsRebuild() {
  if (!fs.existsSync(shaderLabDist)) return true;
  const distMtime = fs.statSync(shaderLabDist).mtimeMs;
  const srcFiles = findFiles(shaderLabSrc, ".ts");
  return srcFiles.some((f) => fs.statSync(f).mtimeMs > distMtime);
}

if (needsRebuild()) {
  console.log("shader-lab dist is stale or missing, rebuilding...");
  execSync("npx cross-env BUILD_TYPE=MODULE NODE_ENV=release rollup -c", { cwd: ROOT, stdio: "inherit" });
}

// Load ShaderLab — this transitively loads engine-core,
// which runs ShaderPool.init() and registers all include fragments.
const { ShaderLab } = await import(pathToFileURL(shaderLabDist).href);
const shaderLab = new ShaderLab();

if (typeof shaderLab._precompile !== "function") {
  console.error("Error: ShaderLab._precompile not available. Rebuild shader-lab first.");
  process.exit(1);
}

/**
 * Precompile a single .shader file and write the .gsp output.
 */
function precompileSingle(shaderPath) {
  const source = fs.readFileSync(shaderPath, "utf-8");
  const relativePath = path.relative(SHADERS_DIR, shaderPath);
  const gspRelative = relativePath.replace(/\.shader$/, ".gsp");
  const gspPath = path.join(LIBS_DIR, gspRelative);

  const gspDir = path.dirname(gspPath);
  if (!fs.existsSync(gspDir)) {
    fs.mkdirSync(gspDir, { recursive: true });
  }

  try {
    const precompiled = shaderLab._precompile(source, 0);
    fs.writeFileSync(gspPath, JSON.stringify(precompiled));
    console.log(`  ${relativePath} → libs/${gspRelative}`);
  } catch (e) {
    console.error(`  FAILED: ${relativePath}`);
    console.error(e);
    return false;
  }
  return true;
}

/**
 * Recursively find all files with a given extension in a directory.
 */
function findFiles(dir, ext) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findFiles(fullPath, ext));
    } else if (entry.name.endsWith(ext)) {
      results.push(fullPath);
    }
  }
  return results;
}

/**
 * Parse src/Shaders/index.ts to extract variable name ↔ relative path mappings.
 * Returns Map<relativePath (no ext), variableName>.
 */
function parseShadersIndex() {
  const indexPath = path.join(SHADERS_DIR, "index.ts");
  const content = fs.readFileSync(indexPath, "utf-8");
  const importReg = /import\s+(\w+)\s+from\s+"\.\/(.+?)\.shader"/g;
  const map = new Map();
  let match;
  while ((match = importReg.exec(content)) !== null) {
    map.set(match[2], match[1]); // e.g. "PostProcess/Uber" → "UberShaderSource"
  }
  return map;
}

/**
 * Generate libs/index.ts based on actual .gsp files on disk.
 * Uses variable names from src/Shaders/index.ts.
 */
function generateLibsIndex() {
  const nameMap = parseShadersIndex();
  const gspFiles = findFiles(LIBS_DIR, ".gsp");
  const entries = [];

  for (const gspFile of gspFiles) {
    const rel = path.relative(LIBS_DIR, gspFile).replace(/\\/g, "/").replace(/\.gsp$/, "");
    const varName = nameMap.get(rel);
    if (!varName) continue; // gsp exists but not in Shaders/index.ts, skip
    const importPath = "./" + rel + ".gsp";
    entries.push({ varName, importPath });
  }

  entries.sort((a, b) => a.varName.localeCompare(b.varName));

  const imports = entries.map((e) => `import ${e.varName} from "${e.importPath}";`).join("\n");
  const exports = entries.map((e) => `  ${e.varName}`).join(",\n");
  const content = `// Auto-generated by precompile-shaders.mjs — do not edit manually\n${imports}\n\nexport {\n${exports}\n};\n`;

  const indexPath = path.join(LIBS_DIR, "index.ts");
  const existing = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, "utf-8") : "";
  if (content !== existing) {
    fs.writeFileSync(indexPath, content);
    console.log("  Updated libs/index.ts");
  }
}

/**
 * Remove .gsp files that have no corresponding .shader source.
 * Also removes empty directories left behind.
 */
function cleanOrphanedGsp(shaderFiles) {
  const shaderRelatives = new Set(shaderFiles.map((f) => path.relative(SHADERS_DIR, f).replace(/\.shader$/, "")));
  const gspFiles = findFiles(LIBS_DIR, ".gsp");
  let removed = 0;

  for (const gspFile of gspFiles) {
    const rel = path.relative(LIBS_DIR, gspFile).replace(/\.gsp$/, "");
    if (!shaderRelatives.has(rel)) {
      fs.unlinkSync(gspFile);
      console.log(`  Removed orphaned: libs/${rel}.gsp`);
      removed++;

      // Clean empty parent dirs
      let dir = path.dirname(gspFile);
      while (dir !== LIBS_DIR) {
        if (fs.readdirSync(dir).length === 0) {
          fs.rmdirSync(dir);
        } else {
          break;
        }
        dir = path.dirname(dir);
      }
    }
  }
  return removed;
}

// Main
const singleFile = process.argv[2];
if (singleFile) {
  const absPath = path.resolve(singleFile);
  console.log(`Precompiling single shader: ${path.basename(absPath)}`);
  precompileSingle(absPath);
} else {
  const shaderFiles = findFiles(SHADERS_DIR, ".shader");
  console.log(`Precompiling ${shaderFiles.length} shaders...`);
  let failed = 0;
  for (const file of shaderFiles) {
    if (!precompileSingle(file)) failed++;
  }

  const removed = cleanOrphanedGsp(shaderFiles);

  if (failed > 0) {
    console.warn(`\n${failed} shader(s) failed to precompile (non-fatal).`);
  }
  if (removed > 0) {
    console.log(`Cleaned up ${removed} orphaned .gsp file(s).`);
  }
}

// Always sync libs/index.ts with actual .gsp files on disk
generateLibsIndex();
console.log("Done.");
