// Auto-generated by shaderlab-precompile --emit-index — do not edit
import BackgroundTextureSource from "./Sky/BackgroundTexture.gsp";
import BlinnPhongSource from "./BlinnPhong.gsp";
import BlitScreenSource from "./Utility/BlitScreen.gsp";
import BlitSource from "./Utility/Blit.gsp";
import BloomSource from "./PostProcess/Bloom.gsp";
import DepthOnlySource from "./Utility/DepthOnly.gsp";
import FinalAntiAliasingSource from "./PostProcess/FinalAntiAliasing.gsp";
import FinalSRGBSource from "./PostProcess/FinalSRGB.gsp";
import ParticleFeedbackSource from "./ParticleFeedback.gsp";
import ParticleSource from "./Particle.gsp";
import PBRSource from "./PBR.gsp";
import ScalableAmbientOcclusionSource from "./AO/ScalableAmbientOcclusion.gsp";
import ShadowMapSource from "./Utility/ShadowMap.gsp";
import SkyboxSource from "./Sky/Skybox.gsp";
import SkyProceduralSource from "./Sky/SkyProcedural.gsp";
import SpriteMaskSource from "./2D/SpriteMask.gsp";
import SpriteSource from "./2D/Sprite.gsp";
import TextSource from "./2D/Text.gsp";
import TrailSource from "./2D/Trail.gsp";
import UberSource from "./PostProcess/Uber.gsp";
import UIDefaultSource from "./2D/UIDefault.gsp";
import UnlitSource from "./Unlit.gsp";

export {
  BackgroundTextureSource,
  BlinnPhongSource,
  BlitScreenSource,
  BlitSource,
  BloomSource,
  DepthOnlySource,
  FinalAntiAliasingSource,
  FinalSRGBSource,
  ParticleFeedbackSource,
  ParticleSource,
  PBRSource,
  ScalableAmbientOcclusionSource,
  ShadowMapSource,
  SkyboxSource,
  SkyProceduralSource,
  SpriteMaskSource,
  SpriteSource,
  TextSource,
  TrailSource,
  UberSource,
  UIDefaultSource,
  UnlitSource
};
