uniform O3_VERTEX_PRECISION mat4 u_localMat;
uniform O3_VERTEX_PRECISION mat4 u_modelMat;
uniform O3_VERTEX_PRECISION mat4 u_viewMat;
uniform O3_VERTEX_PRECISION mat4 u_projMat;
uniform O3_VERTEX_PRECISION mat4 u_MVMat;
uniform O3_VERTEX_PRECISION mat4 u_MVPMat;
uniform O3_VERTEX_PRECISION mat3 u_normalMat;
uniform O3_VERTEX_PRECISION vec3 u_cameraPos;
uniform O3_VERTEX_PRECISION float u_time;
