// Auto-generated by shader-compiler-precompile --emit-sources — do not edit.

import type { IShaderSource } from "../Shaders";
import BlinnPhong_ForwardPassBlinnPhong from "./BlinnPhong/ForwardPassBlinnPhong.glsl";
import BlinnPhong_MobileBlinnPhong from "./BlinnPhong/MobileBlinnPhong.glsl";
import Blit_BlitVertex from "./Blit/BlitVertex.glsl";
import Common_Attributes from "./Common/Attributes.glsl";
import Common_Common from "./Common/Common.glsl";
import Common_Fog from "./Common/Fog.glsl";
import Common_Normal from "./Common/Normal.glsl";
import Common_Transform from "./Common/Transform.glsl";
import Lighting_AmbientOcclusion_BilateralBlur from "./Lighting/AmbientOcclusion/BilateralBlur.glsl";
import Lighting_AmbientOcclusion_ScalableAmbientOcclusion from "./Lighting/AmbientOcclusion/ScalableAmbientOcclusion.glsl";
import Lighting_Light from "./Lighting/Light.glsl";
import Noise_NoiseCommon from "./Noise/NoiseCommon.glsl";
import Noise_NoiseSimplexGrad from "./Noise/NoiseSimplexGrad.glsl";
import PBR_BSDF from "./PBR/BSDF.glsl";
import PBR_ForwardPassPBR from "./PBR/ForwardPassPBR.glsl";
import PBR_FragmentPBR from "./PBR/FragmentPBR.glsl";
import PBR_LightDirectPBR from "./PBR/LightDirectPBR.glsl";
import PBR_LightIndirectFunctions from "./PBR/LightIndirectFunctions.glsl";
import PBR_LightIndirectPBR from "./PBR/LightIndirectPBR.glsl";
import PBR_ReflectionLobe from "./PBR/ReflectionLobe.glsl";
import PBR_Refraction from "./PBR/Refraction.glsl";
import PBR_VaryingsPBR from "./PBR/VaryingsPBR.glsl";
import PBR_VertexPBR from "./PBR/VertexPBR.glsl";
import Particle_Billboard_HorizontalBillboard from "./Particle/Billboard/HorizontalBillboard.glsl";
import Particle_Billboard_SphereBillboard from "./Particle/Billboard/SphereBillboard.glsl";
import Particle_Billboard_StretchedBillboard from "./Particle/Billboard/StretchedBillboard.glsl";
import Particle_Billboard_VerticalBillboard from "./Particle/Billboard/VerticalBillboard.glsl";
import Particle_Module_ColorOverLifetime from "./Particle/Module/ColorOverLifetime.glsl";
import Particle_Module_ForceOverLifetime from "./Particle/Module/ForceOverLifetime.glsl";
import Particle_Module_LimitVelocityOverLifetime from "./Particle/Module/LimitVelocityOverLifetime.glsl";
import Particle_Module_NoiseModule from "./Particle/Module/NoiseModule.glsl";
import Particle_Module_RotationOverLifetime from "./Particle/Module/RotationOverLifetime.glsl";
import Particle_Module_SizeOverLifetime from "./Particle/Module/SizeOverLifetime.glsl";
import Particle_Module_TextureSheetAnimation from "./Particle/Module/TextureSheetAnimation.glsl";
import Particle_Module_VelocityOverLifetime from "./Particle/Module/VelocityOverLifetime.glsl";
import Particle_ParticleCommon from "./Particle/ParticleCommon.glsl";
import Particle_ParticleMesh from "./Particle/ParticleMesh.glsl";
import Particle_ParticleVert from "./Particle/ParticleVert.glsl";
import PostProcess_Bloom_BloomBlurH from "./PostProcess/Bloom/BloomBlurH.glsl";
import PostProcess_Bloom_BloomBlurV from "./PostProcess/Bloom/BloomBlurV.glsl";
import PostProcess_Bloom_BloomPrefilter from "./PostProcess/Bloom/BloomPrefilter.glsl";
import PostProcess_Bloom_BloomUpsample from "./PostProcess/Bloom/BloomUpsample.glsl";
import PostProcess_FXAA_FXAA3_11 from "./PostProcess/FXAA/FXAA3_11.glsl";
import PostProcess_Filtering from "./PostProcess/Filtering.glsl";
import PostProcess_FinalAntiAliasing from "./PostProcess/FinalAntiAliasing.glsl";
import PostProcess_FinalSRGB from "./PostProcess/FinalSRGB.glsl";
import PostProcess_PostCommon from "./PostProcess/PostCommon.glsl";
import PostProcess_Tonemapping_ACES_ColorTransform from "./PostProcess/Tonemapping/ACES/ColorTransform.glsl";
import PostProcess_Tonemapping_ACES_ODT from "./PostProcess/Tonemapping/ACES/ODT.glsl";
import PostProcess_Tonemapping_ACES_RRT from "./PostProcess/Tonemapping/ACES/RRT.glsl";
import PostProcess_Tonemapping_ACES_Tonescale from "./PostProcess/Tonemapping/ACES/Tonescale.glsl";
import PostProcess_Tonemapping_ACESTonemapping from "./PostProcess/Tonemapping/ACESTonemapping.glsl";
import PostProcess_Tonemapping_NeutralTonemapping from "./PostProcess/Tonemapping/NeutralTonemapping.glsl";
import PostProcess_UberPost from "./PostProcess/UberPost.glsl";
import Shadow_Shadow from "./Shadow/Shadow.glsl";
import Shadow_ShadowSampleTent from "./Shadow/ShadowSampleTent.glsl";
import Skin_BlendShape from "./Skin/BlendShape.glsl";
import Skin_Skin from "./Skin/Skin.glsl";

// prettier-ignore
export const shaderLibrary: IShaderSource[] = [
  { source: BlinnPhong_ForwardPassBlinnPhong, path: "ShaderLibrary/BlinnPhong/ForwardPassBlinnPhong.glsl" },
  { source: BlinnPhong_MobileBlinnPhong, path: "ShaderLibrary/BlinnPhong/MobileBlinnPhong.glsl" },
  { source: Blit_BlitVertex, path: "ShaderLibrary/Blit/BlitVertex.glsl" },
  { source: Common_Attributes, path: "ShaderLibrary/Common/Attributes.glsl" },
  { source: Common_Common, path: "ShaderLibrary/Common/Common.glsl" },
  { source: Common_Fog, path: "ShaderLibrary/Common/Fog.glsl" },
  { source: Common_Normal, path: "ShaderLibrary/Common/Normal.glsl" },
  { source: Common_Transform, path: "ShaderLibrary/Common/Transform.glsl" },
  { source: Lighting_AmbientOcclusion_BilateralBlur, path: "ShaderLibrary/Lighting/AmbientOcclusion/BilateralBlur.glsl" },
  { source: Lighting_AmbientOcclusion_ScalableAmbientOcclusion, path: "ShaderLibrary/Lighting/AmbientOcclusion/ScalableAmbientOcclusion.glsl" },
  { source: Lighting_Light, path: "ShaderLibrary/Lighting/Light.glsl" },
  { source: Noise_NoiseCommon, path: "ShaderLibrary/Noise/NoiseCommon.glsl" },
  { source: Noise_NoiseSimplexGrad, path: "ShaderLibrary/Noise/NoiseSimplexGrad.glsl" },
  { source: PBR_BSDF, path: "ShaderLibrary/PBR/BSDF.glsl" },
  { source: PBR_ForwardPassPBR, path: "ShaderLibrary/PBR/ForwardPassPBR.glsl" },
  { source: PBR_FragmentPBR, path: "ShaderLibrary/PBR/FragmentPBR.glsl" },
  { source: PBR_LightDirectPBR, path: "ShaderLibrary/PBR/LightDirectPBR.glsl" },
  { source: PBR_LightIndirectFunctions, path: "ShaderLibrary/PBR/LightIndirectFunctions.glsl" },
  { source: PBR_LightIndirectPBR, path: "ShaderLibrary/PBR/LightIndirectPBR.glsl" },
  { source: PBR_ReflectionLobe, path: "ShaderLibrary/PBR/ReflectionLobe.glsl" },
  { source: PBR_Refraction, path: "ShaderLibrary/PBR/Refraction.glsl" },
  { source: PBR_VaryingsPBR, path: "ShaderLibrary/PBR/VaryingsPBR.glsl" },
  { source: PBR_VertexPBR, path: "ShaderLibrary/PBR/VertexPBR.glsl" },
  { source: Particle_Billboard_HorizontalBillboard, path: "ShaderLibrary/Particle/Billboard/HorizontalBillboard.glsl" },
  { source: Particle_Billboard_SphereBillboard, path: "ShaderLibrary/Particle/Billboard/SphereBillboard.glsl" },
  { source: Particle_Billboard_StretchedBillboard, path: "ShaderLibrary/Particle/Billboard/StretchedBillboard.glsl" },
  { source: Particle_Billboard_VerticalBillboard, path: "ShaderLibrary/Particle/Billboard/VerticalBillboard.glsl" },
  { source: Particle_Module_ColorOverLifetime, path: "ShaderLibrary/Particle/Module/ColorOverLifetime.glsl" },
  { source: Particle_Module_ForceOverLifetime, path: "ShaderLibrary/Particle/Module/ForceOverLifetime.glsl" },
  { source: Particle_Module_LimitVelocityOverLifetime, path: "ShaderLibrary/Particle/Module/LimitVelocityOverLifetime.glsl" },
  { source: Particle_Module_NoiseModule, path: "ShaderLibrary/Particle/Module/NoiseModule.glsl" },
  { source: Particle_Module_RotationOverLifetime, path: "ShaderLibrary/Particle/Module/RotationOverLifetime.glsl" },
  { source: Particle_Module_SizeOverLifetime, path: "ShaderLibrary/Particle/Module/SizeOverLifetime.glsl" },
  { source: Particle_Module_TextureSheetAnimation, path: "ShaderLibrary/Particle/Module/TextureSheetAnimation.glsl" },
  { source: Particle_Module_VelocityOverLifetime, path: "ShaderLibrary/Particle/Module/VelocityOverLifetime.glsl" },
  { source: Particle_ParticleCommon, path: "ShaderLibrary/Particle/ParticleCommon.glsl" },
  { source: Particle_ParticleMesh, path: "ShaderLibrary/Particle/ParticleMesh.glsl" },
  { source: Particle_ParticleVert, path: "ShaderLibrary/Particle/ParticleVert.glsl" },
  { source: PostProcess_Bloom_BloomBlurH, path: "ShaderLibrary/PostProcess/Bloom/BloomBlurH.glsl" },
  { source: PostProcess_Bloom_BloomBlurV, path: "ShaderLibrary/PostProcess/Bloom/BloomBlurV.glsl" },
  { source: PostProcess_Bloom_BloomPrefilter, path: "ShaderLibrary/PostProcess/Bloom/BloomPrefilter.glsl" },
  { source: PostProcess_Bloom_BloomUpsample, path: "ShaderLibrary/PostProcess/Bloom/BloomUpsample.glsl" },
  { source: PostProcess_FXAA_FXAA3_11, path: "ShaderLibrary/PostProcess/FXAA/FXAA3_11.glsl" },
  { source: PostProcess_Filtering, path: "ShaderLibrary/PostProcess/Filtering.glsl" },
  { source: PostProcess_FinalAntiAliasing, path: "ShaderLibrary/PostProcess/FinalAntiAliasing.glsl" },
  { source: PostProcess_FinalSRGB, path: "ShaderLibrary/PostProcess/FinalSRGB.glsl" },
  { source: PostProcess_PostCommon, path: "ShaderLibrary/PostProcess/PostCommon.glsl" },
  { source: PostProcess_Tonemapping_ACES_ColorTransform, path: "ShaderLibrary/PostProcess/Tonemapping/ACES/ColorTransform.glsl" },
  { source: PostProcess_Tonemapping_ACES_ODT, path: "ShaderLibrary/PostProcess/Tonemapping/ACES/ODT.glsl" },
  { source: PostProcess_Tonemapping_ACES_RRT, path: "ShaderLibrary/PostProcess/Tonemapping/ACES/RRT.glsl" },
  { source: PostProcess_Tonemapping_ACES_Tonescale, path: "ShaderLibrary/PostProcess/Tonemapping/ACES/Tonescale.glsl" },
  { source: PostProcess_Tonemapping_ACESTonemapping, path: "ShaderLibrary/PostProcess/Tonemapping/ACESTonemapping.glsl" },
  { source: PostProcess_Tonemapping_NeutralTonemapping, path: "ShaderLibrary/PostProcess/Tonemapping/NeutralTonemapping.glsl" },
  { source: PostProcess_UberPost, path: "ShaderLibrary/PostProcess/UberPost.glsl" },
  { source: Shadow_Shadow, path: "ShaderLibrary/Shadow/Shadow.glsl" },
  { source: Shadow_ShadowSampleTent, path: "ShaderLibrary/Shadow/ShadowSampleTent.glsl" },
  { source: Skin_BlendShape, path: "ShaderLibrary/Skin/BlendShape.glsl" },
  { source: Skin_Skin, path: "ShaderLibrary/Skin/Skin.glsl" },
];
