// Auto-generated by scripts/generate-shader-library-index.js — do not edit.
// Source files are scanned from this directory; includeKey = path relative to ShaderLibrary/.

import AO_BilateralBlur from "./AO/BilateralBlur.glsl";
import AO_ScalableAmbientOcclusion from "./AO/ScalableAmbientOcclusion.glsl";
import BlinnPhong_ForwardPassBlinnPhong from "./BlinnPhong/ForwardPassBlinnPhong.glsl";
import Common_Attributes from "./Common/Attributes.glsl";
import Common_BlitVertex from "./Common/BlitVertex.glsl";
import Common_Color from "./Common/Color.glsl";
import Common_Common from "./Common/Common.glsl";
import Common_Fog from "./Common/Fog.glsl";
import Common_Light from "./Common/Light.glsl";
import Common_MobileBlinnPhong from "./Common/MobileBlinnPhong.glsl";
import Common_Normal from "./Common/Normal.glsl";
import Common_Position from "./Common/Position.glsl";
import Common_PositionClipSpace from "./Common/PositionClipSpace.glsl";
import Common_Transform from "./Common/Transform.glsl";
import Common_UV from "./Common/UV.glsl";
import Common_ViewDirection from "./Common/ViewDirection.glsl";
import Common_WorldPosition from "./Common/WorldPosition.glsl";
import Noise_NoiseCommon from "./Noise/NoiseCommon.glsl";
import Noise_NoiseSimplexGrad from "./Noise/NoiseSimplexGrad.glsl";
import PBR_BSDF from "./PBR/BSDF.glsl";
import PBR_ForwardPassPBR from "./PBR/ForwardPassPBR.glsl";
import PBR_FragmentPBR from "./PBR/FragmentPBR.glsl";
import PBR_LightDirectPBR from "./PBR/LightDirectPBR.glsl";
import PBR_LightIndirectFunctions from "./PBR/LightIndirectFunctions.glsl";
import PBR_LightIndirectPBR from "./PBR/LightIndirectPBR.glsl";
import PBR_ReflectionLobe from "./PBR/ReflectionLobe.glsl";
import PBR_Refraction from "./PBR/Refraction.glsl";
import PBR_VaryingsPBR from "./PBR/VaryingsPBR.glsl";
import PBR_VertexPBR from "./PBR/VertexPBR.glsl";
import Particle_Billboard_HorizontalBillboard from "./Particle/Billboard/HorizontalBillboard.glsl";
import Particle_Billboard_SphereBillboard from "./Particle/Billboard/SphereBillboard.glsl";
import Particle_Billboard_StretchedBillboard from "./Particle/Billboard/StretchedBillboard.glsl";
import Particle_Billboard_VerticalBillboard from "./Particle/Billboard/VerticalBillboard.glsl";
import Particle_Module_ColorOverLifetime from "./Particle/Module/ColorOverLifetime.glsl";
import Particle_Module_ForceOverLifetime from "./Particle/Module/ForceOverLifetime.glsl";
import Particle_Module_LimitVelocityOverLifetime from "./Particle/Module/LimitVelocityOverLifetime.glsl";
import Particle_Module_NoiseModule from "./Particle/Module/NoiseModule.glsl";
import Particle_Module_RotationOverLifetime from "./Particle/Module/RotationOverLifetime.glsl";
import Particle_Module_SizeOverLifetime from "./Particle/Module/SizeOverLifetime.glsl";
import Particle_Module_TextureSheetAnimation from "./Particle/Module/TextureSheetAnimation.glsl";
import Particle_Module_VelocityOverLifetime from "./Particle/Module/VelocityOverLifetime.glsl";
import Particle_ParticleCommon from "./Particle/ParticleCommon.glsl";
import Particle_ParticleFeedback from "./Particle/ParticleFeedback.glsl";
import Particle_ParticleMesh from "./Particle/ParticleMesh.glsl";
import PostProcess_Bloom_BloomBlurH from "./PostProcess/Bloom/BloomBlurH.glsl";
import PostProcess_Bloom_BloomBlurV from "./PostProcess/Bloom/BloomBlurV.glsl";
import PostProcess_Bloom_BloomPrefilter from "./PostProcess/Bloom/BloomPrefilter.glsl";
import PostProcess_Bloom_BloomUpsample from "./PostProcess/Bloom/BloomUpsample.glsl";
import PostProcess_FXAA_FXAA3_11 from "./PostProcess/FXAA/FXAA3_11.glsl";
import PostProcess_Filtering from "./PostProcess/Filtering.glsl";
import PostProcess_FinalAntiAliasing from "./PostProcess/FinalAntiAliasing.glsl";
import PostProcess_FinalSRGB from "./PostProcess/FinalSRGB.glsl";
import PostProcess_PostCommon from "./PostProcess/PostCommon.glsl";
import PostProcess_Tonemapping_ACES_ColorTransform from "./PostProcess/Tonemapping/ACES/ColorTransform.glsl";
import PostProcess_Tonemapping_ACES_ODT from "./PostProcess/Tonemapping/ACES/ODT.glsl";
import PostProcess_Tonemapping_ACES_RRT from "./PostProcess/Tonemapping/ACES/RRT.glsl";
import PostProcess_Tonemapping_ACES_Tonescale from "./PostProcess/Tonemapping/ACES/Tonescale.glsl";
import PostProcess_Tonemapping_ACESTonemapping from "./PostProcess/Tonemapping/ACESTonemapping.glsl";
import PostProcess_Tonemapping_NeutralTonemapping from "./PostProcess/Tonemapping/NeutralTonemapping.glsl";
import PostProcess_UberPost from "./PostProcess/UberPost.glsl";
import Shadow_Shadow from "./Shadow/Shadow.glsl";
import Shadow_ShadowSampleTent from "./Shadow/ShadowSampleTent.glsl";
import Skin_BlendShape from "./Skin/BlendShape.glsl";
import Skin_Skin from "./Skin/Skin.glsl";

interface IShaderFragment {
  includeKey: string;
  source: string;
}

const fragmentList: IShaderFragment[] = [
  { source: AO_BilateralBlur, includeKey: "AO/BilateralBlur.glsl" },
  { source: AO_ScalableAmbientOcclusion, includeKey: "AO/ScalableAmbientOcclusion.glsl" },
  { source: BlinnPhong_ForwardPassBlinnPhong, includeKey: "BlinnPhong/ForwardPassBlinnPhong.glsl" },
  { source: Common_Attributes, includeKey: "Common/Attributes.glsl" },
  { source: Common_BlitVertex, includeKey: "Common/BlitVertex.glsl" },
  { source: Common_Color, includeKey: "Common/Color.glsl" },
  { source: Common_Common, includeKey: "Common/Common.glsl" },
  { source: Common_Fog, includeKey: "Common/Fog.glsl" },
  { source: Common_Light, includeKey: "Common/Light.glsl" },
  { source: Common_MobileBlinnPhong, includeKey: "Common/MobileBlinnPhong.glsl" },
  { source: Common_Normal, includeKey: "Common/Normal.glsl" },
  { source: Common_Position, includeKey: "Common/Position.glsl" },
  { source: Common_PositionClipSpace, includeKey: "Common/PositionClipSpace.glsl" },
  { source: Common_Transform, includeKey: "Common/Transform.glsl" },
  { source: Common_UV, includeKey: "Common/UV.glsl" },
  { source: Common_ViewDirection, includeKey: "Common/ViewDirection.glsl" },
  { source: Common_WorldPosition, includeKey: "Common/WorldPosition.glsl" },
  { source: Noise_NoiseCommon, includeKey: "Noise/NoiseCommon.glsl" },
  { source: Noise_NoiseSimplexGrad, includeKey: "Noise/NoiseSimplexGrad.glsl" },
  { source: PBR_BSDF, includeKey: "PBR/BSDF.glsl" },
  { source: PBR_ForwardPassPBR, includeKey: "PBR/ForwardPassPBR.glsl" },
  { source: PBR_FragmentPBR, includeKey: "PBR/FragmentPBR.glsl" },
  { source: PBR_LightDirectPBR, includeKey: "PBR/LightDirectPBR.glsl" },
  { source: PBR_LightIndirectFunctions, includeKey: "PBR/LightIndirectFunctions.glsl" },
  { source: PBR_LightIndirectPBR, includeKey: "PBR/LightIndirectPBR.glsl" },
  { source: PBR_ReflectionLobe, includeKey: "PBR/ReflectionLobe.glsl" },
  { source: PBR_Refraction, includeKey: "PBR/Refraction.glsl" },
  { source: PBR_VaryingsPBR, includeKey: "PBR/VaryingsPBR.glsl" },
  { source: PBR_VertexPBR, includeKey: "PBR/VertexPBR.glsl" },
  { source: Particle_Billboard_HorizontalBillboard, includeKey: "Particle/Billboard/HorizontalBillboard.glsl" },
  { source: Particle_Billboard_SphereBillboard, includeKey: "Particle/Billboard/SphereBillboard.glsl" },
  { source: Particle_Billboard_StretchedBillboard, includeKey: "Particle/Billboard/StretchedBillboard.glsl" },
  { source: Particle_Billboard_VerticalBillboard, includeKey: "Particle/Billboard/VerticalBillboard.glsl" },
  { source: Particle_Module_ColorOverLifetime, includeKey: "Particle/Module/ColorOverLifetime.glsl" },
  { source: Particle_Module_ForceOverLifetime, includeKey: "Particle/Module/ForceOverLifetime.glsl" },
  { source: Particle_Module_LimitVelocityOverLifetime, includeKey: "Particle/Module/LimitVelocityOverLifetime.glsl" },
  { source: Particle_Module_NoiseModule, includeKey: "Particle/Module/NoiseModule.glsl" },
  { source: Particle_Module_RotationOverLifetime, includeKey: "Particle/Module/RotationOverLifetime.glsl" },
  { source: Particle_Module_SizeOverLifetime, includeKey: "Particle/Module/SizeOverLifetime.glsl" },
  { source: Particle_Module_TextureSheetAnimation, includeKey: "Particle/Module/TextureSheetAnimation.glsl" },
  { source: Particle_Module_VelocityOverLifetime, includeKey: "Particle/Module/VelocityOverLifetime.glsl" },
  { source: Particle_ParticleCommon, includeKey: "Particle/ParticleCommon.glsl" },
  { source: Particle_ParticleFeedback, includeKey: "Particle/ParticleFeedback.glsl" },
  { source: Particle_ParticleMesh, includeKey: "Particle/ParticleMesh.glsl" },
  { source: PostProcess_Bloom_BloomBlurH, includeKey: "PostProcess/Bloom/BloomBlurH.glsl" },
  { source: PostProcess_Bloom_BloomBlurV, includeKey: "PostProcess/Bloom/BloomBlurV.glsl" },
  { source: PostProcess_Bloom_BloomPrefilter, includeKey: "PostProcess/Bloom/BloomPrefilter.glsl" },
  { source: PostProcess_Bloom_BloomUpsample, includeKey: "PostProcess/Bloom/BloomUpsample.glsl" },
  { source: PostProcess_FXAA_FXAA3_11, includeKey: "PostProcess/FXAA/FXAA3_11.glsl" },
  { source: PostProcess_Filtering, includeKey: "PostProcess/Filtering.glsl" },
  { source: PostProcess_FinalAntiAliasing, includeKey: "PostProcess/FinalAntiAliasing.glsl" },
  { source: PostProcess_FinalSRGB, includeKey: "PostProcess/FinalSRGB.glsl" },
  { source: PostProcess_PostCommon, includeKey: "PostProcess/PostCommon.glsl" },
  { source: PostProcess_Tonemapping_ACES_ColorTransform, includeKey: "PostProcess/Tonemapping/ACES/ColorTransform.glsl" },
  { source: PostProcess_Tonemapping_ACES_ODT, includeKey: "PostProcess/Tonemapping/ACES/ODT.glsl" },
  { source: PostProcess_Tonemapping_ACES_RRT, includeKey: "PostProcess/Tonemapping/ACES/RRT.glsl" },
  { source: PostProcess_Tonemapping_ACES_Tonescale, includeKey: "PostProcess/Tonemapping/ACES/Tonescale.glsl" },
  { source: PostProcess_Tonemapping_ACESTonemapping, includeKey: "PostProcess/Tonemapping/ACESTonemapping.glsl" },
  { source: PostProcess_Tonemapping_NeutralTonemapping, includeKey: "PostProcess/Tonemapping/NeutralTonemapping.glsl" },
  { source: PostProcess_UberPost, includeKey: "PostProcess/UberPost.glsl" },
  { source: Shadow_Shadow, includeKey: "Shadow/Shadow.glsl" },
  { source: Shadow_ShadowSampleTent, includeKey: "Shadow/ShadowSampleTent.glsl" },
  { source: Skin_BlendShape, includeKey: "Skin/BlendShape.glsl" },
  { source: Skin_Skin, includeKey: "Skin/Skin.glsl" },
];

export { fragmentList };
