name: Set author email

on:
  pull_request:
    types: [closed]

jobs:
  set-author-email:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: galacean/shared-actions/set-author-email@main
