name: Set author email

on:
  push:
    branches: [main, 'dev/**']

jobs:
  set-author-email:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: galacean/shared-actions/set-author-email@main
