name: Trigger Website Build

on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  trigger-website:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger website build
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: Bearer ${{ secrets.WEBSITE_TRIGGER_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/galacean/website/dispatches \
        -d '{"event_type": "engine_update","client_payload": {"engine_commit": "${{ github.event.head_commit.message }}"}}'
